const galleryData = [
    {
        artist:'Amaya Eguizábal',
        genre:'Animals',
        images:[
            {
                title:'Parakeet',
                imageSource:'bird.jpg',
                altText:'Parakeet on back of furniture.',
                description:'Parakeet on back of furniture.',
                tags:['Animals'],
                class:'animals',
                id:'bird',
            },
            {
                title:'Hedgehog',
                imageSource:'hedgehog.jpg',
                altText:'Hedgehog looking at the camera.',
                description:'Hedgehog looking at the camera.',
                tags:['Animals'],
                class:'animals',
                id:'hedgehog',
            },
            {
                title:'Cat with roses',
                imageSource:'cat.jpg',
                altText:'Cat lounging next to vase of roses.',
                description:'Cat lounging next to vase of roses.',
                tags:['Animals'],
                class:'animals',
                id:'cat',
            },
            {
                title:'Brown and white dog',
                imageSource:'dogTerrier.jpg',
                altText:'Brown and white colored terrier.',
                description:'Brown and white colored terrier.',
                tags:['Animals'],
                class:'animals',
                id:'dogTerrier',
            },
            {
                title:'Black Labrador',
                imageSource:'dogBlack.jpg',
                altText:'Black labrador snuggled on a white bed.',
                description:'Black labrador snuggled on a white bed.',
                tags:['Animals'],
                class:'animals',
                id:'dogBlack',
            },
            {
                title:'Dog and guinea pig',
                imageSource:'dogBrown.jpg',
                altText:'Black mouth cur laying next to a guinea pig.',
                description:'Black mouth cur laying next to a guinea pig.',
                tags:['Animals'],
                class:'animals',
                id:'dogBrown',
            },
        ],
        acknowledgement:`Images by <a href="https://pixabay.com/users/amayaeguizabal-151412/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1215159">Amaya Eguizábal</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1215159">Pixabay</a>`
    },
    {
        artist:'Bessi',
        genre:'Nature',
        images:[
            {
                title:'Tree in sun rays',
                imageSource:'treeSunlight.jpg',
                altText:'Tree in field lit by cloud breaking sun rays.',
                description:'Tree in field lit by cloud breaking sun rays.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treeSunlight',
            },
            {
                title:'Tree with red flowers',
                imageSource:'treeRoses.jpg',
                altText:'Tree in green field with red flowers.',
                description:'Tree in green field with red flowers.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treeRoses',
            },
            {
                title:'Spring tree',
                imageSource:'treeSpring.jpg',
                altText:'Tree in field with leaves just starting to leaf out.',
                description:'Tree in field with leaves just starting to leaf out.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treeSpring',
            },
            {
                title:'Summer tree',
                imageSource:'treeSummer.jpg',
                altText:'Tree in field with full grown summer leaves.',
                description:'Tree in field with full grown summer leaves.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treeSummer',
            },
            {
                title:'Fall tree',
                imageSource:'treeFall.jpg',
                altText:'Tree in field with leaves turning orange for fall.',
                description:'Tree in field with leaves and orange for fall.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treeFall',
            },
            {
                title:'Tree on purple sunset',
                imageSource:'treePurple.jpg',
                altText:'Tree with purple sky and clouds as backdrop.',
                description:'Tree with purple sky and clouds as backdrop.',
                tags:['Trees','Nature'],
                class:'trees',
                id:'treePurple',
            },
        ],
        acknowledgement:`Images by <a href="https://pixabay.com/users/bessi-909086/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=736885">bess.hamiti@gmail.com</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=736885">Pixabay</a>`
    },
    {
        artist:'Margit Wallner',
        genre:'Macro',
        images:[
            {
                title:'Droplets',
                imageSource:'droplets.jpg',
                altText:'Two water droplets reflecting a flower.',
                description:'Two water droplets reflecting a flower.',
                tags:['Macro'],
                class:'macro',
                id:'droplets',
            },
            {
                title:'Fire',
                imageSource:'fire.jpg',
                altText:'Lit match. Smoke has a blue tint',
                description:'Burniing match with smoke with a blue tint.',
                tags:['Macro'],
                class:'macro',
                id:'fire',
            },
            {
                title:'Light bulb',
                imageSource:'lightBulb.jpg',
                altText:'Lit light bulb with sparks radiating from behind it.',
                description:'Lit light bulb with sparks radiating from behind it.',
                tags:['Macro'],
                class:'macro',
                id:'lightBulb',
            },
            {
                title:'Soap Bubbles',
                imageSource:'soapBubbles.jpg',
                altText:'Soap bubbles resting in the snow.',
                description:'Soap bubbles resting in the snow.',
                tags:['Macro'],
                class:'macro',
                id:'soapBubbles',
            },
            {
                title:'Strawberry in milk.',
                imageSource:'strawberyMilk.jpg',
                altText:'Strawberry dropped into spoonful of milk',
                description:'Strawberry dropped into spoonful of milk.',
                tags:['Macro'],
                class:'macro',
                id:'strawberryMilk',
            },
            {
                title:'Water drop',
                imageSource:'waterDrop.jpg',
                altText:'Water drop hitting the water.',
                description:'Water drop hitting the water with yellow hue.',
                tags:['Macro'],
                class:'macro',
                id:'waterDrop',
            },
        ],
        acknowledgement:`Images by <a href="https://pixabay.com/users/wallner-974517/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5267300">Margit Wallner</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5267300">Pixabay</a>`
    },
];

export {galleryData};

// Animals Amaya Eguizábal Image by <a href="https://pixabay.com/users/amayaeguizabal-151412/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1215159">Amaya Eguizábal</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1215159">Pixabay</a>

// Nature trees Bessi Image by <a href="https://pixabay.com/users/bessi-909086/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=736885">bess.hamiti@gmail.com</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=736885">Pixabay</a>

// Macro Margit Wallner Image by <a href="https://pixabay.com/users/wallner-974517/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5267300">Margit Wallner</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5267300">Pixabay</a>